spring:
  application:
    name: accountService
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enable: true
  jpa:
    datasource-platform: org.hibernate.dialect:H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

accounts:
  message: "This is the contact person information"
  contactDetails:
    name: "harsh fuzele"
    email: "harshfulzele@gmail.com"
  onCallSupport:
    - (333)333
    - (555)555

